extends Control

func _ready():
	$AnimationPlayer.play("intro")
	yield($AnimationPlayer, "animation_finished")
	$Textbox.set_name("Hanyuu")
	$Textbox.add_to_queue("\"Welcome to dark Rika corner!\"")
	$Textbox.set_blip($Textbox.blips["blip80"])
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(4), "timeout")
	$Textbox.set_blip($Textbox.blips["blip75"])
	$Textbox.set_name("Rika")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Also known as 'tea party'...\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip80"])
	$Textbox.set_name("Hanyuu")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Hau au ! Today we have a very special guest!\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip70"])
	$Textbox.set_name("Rika")
	$Textbox.clear()
	$Textbox.add_to_queue("\"A guest...? Oh, I wonder who they are.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip60"])
	$Textbox.set_name("Zumo")
	$Textbox.clear()
	$Textbox.add_to_queue("\"It is I, Zumo! Creator of this fangame, doing a blatant self-insert.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip60"])
	$Textbox.set_name("Zumo")
	$Textbox.clear()
	$Textbox.add_to_queue("\"I came here to talk about the game...\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip70"])
	$Textbox.set_name("Rika")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Then you shouldn't have come here.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip80"])
	$Textbox.set_name("Hanyuu")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Hauauau... Rika, don't be so mean!\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip75"])
	$Textbox.set_name("Rika")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Fine.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(2.5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip60"])
	$Textbox.set_name("Zumo")
	$Textbox.clear()
	$Textbox.add_to_queue("\"...Anyway. I just wanted to thank you for getting this far and finishing the game.\nThis is my first serious project and I'm very happy with how it turned out.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip60"])
	$Textbox.set_name("Zumo")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Looking back now, there are many things that could be improved or redesigned.\nHowever, the deadline is drawing close, and I can't spend as much time programming as months ago.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip60"])
	$Textbox.set_name("Zumo")
	$Textbox.clear()
	$Textbox.add_to_queue("\"I've decided to release the source code for everyone to freely use under\the very permissive MIT license. I will upload the game's source code to Github for everyone\nto use as they want.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip60"])
	$Textbox.set_name("Zumo")
	$Textbox.clear()
	$Textbox.add_to_queue("\"I also wanted to tell you to go support Umineko and Higurashi on Steam!\nBuy the games and play them, it's worth every penny.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip75"])
	$Textbox.set_name("Rika")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Is that all?\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip60"])
	$Textbox.set_name("Zumo")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Pretty much. Thanks for having me here, girls.\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(4), "timeout")
	$Textbox.set_blip($Textbox.blips["blip80"])
	$Textbox.set_name("Hanyuu")
	$Textbox.clear()
	$Textbox.add_to_queue("\"It's nothing!\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(2.5), "timeout")
	$Textbox.set_blip($Textbox.blips["blip75"])
	$Textbox.set_name("Rika")
	$Textbox.clear()
	$Textbox.add_to_queue("\"Anyway, here ends this episode of 'Dark Rika corner'! See you next time!\"")
	yield($Textbox.label, "on_queue_end")
	yield(get_tree().create_timer(5), "timeout")
	$AnimationPlayer.play("outro")
	yield($AnimationPlayer, "animation_finished")
	miracle.load_scene("res://src/intro.tscn")
